spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true

server:
  servlet:
    context-path: /ocr

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml



socr:
  baseUrl: http://www.baidu.com
