spring:
  datasource:
    url: jdbc:mysql://115.29.238.138:3306/ocr_services2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      connection-test-query: SELECT 1 FROM DUAL
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: PrimaryHikariCP
      max-lifetime: 60000
      connection-timeout: 30000

oss:
  endpointWeb: https://oss-cn-hk-hsbc-d01-a.ali-ops.cloud.cn.hsbc/
  endpointEcs: http://oss-cn-hk-hsbc-d01-a.ali-ops.cloud.cn.hsbc/
  accessKeyId: 11
  accessKeySecret: 11
  bucketName: cdg-ocr-oss




socr:
  idcard:
    baseUrl: http://172.21.4.145/
  business:
    baseUrl: http://172.21.5.83/
  vat:
    baseUrl: http://172.21.15.108/