apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bbdm
  namespace: 4pd
  labels:
    app: hsbc-bbdm
spec:
  selector:
     matchLabels:
        app: hsbc-bbdm
  replicas: 1
  template:
      metadata:
        labels:
          app: hsbc-bbdm
      spec:
        containers:
        - name: bbdm
          image: 115.29.238.138:5000/bbdm-svc:v_20210723231257
          imagePullPolicy: IfNotPresent
          workingDir: /root
          env:
          - name: TZ
            value: Asia/Shanghai
          volumeMounts:
          - name: bbdm-conf
            mountPath: /root/bbdm/conf
          ports:
          - name: web
            containerPort: 8082
            hostPort: 8082
          resources:
            limits:
              cpu: 8000m
              memory: 16Gi
            requests:
              cpu: 500m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /ocr/actuator/health
              port: 8082
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 10
        volumes:
        - name: bbdm-conf
          configMap:
            name: bbdm-conf



---

apiVersion: v1
kind: Service
metadata:
  name: bbdm-svc
  namespace: 4pd
spec:
  ports:
  - name: web
    nodePort: 30027
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: hsbc-bbdm
  type: NodePort


---
apiVersion: v1
kind: Namespace
metadata:
  name: 4pd
