apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bbdm
  namespace: 4pd
  labels:
    app: hsbc-bbdm
spec:
  selector:
     matchLabels:
        app: hsbc-bbdm
  replicas: 1
  template:
      metadata:
        labels:
          app: hsbc-bbdm
      spec:
        containers:
        - name: bbdm
          image: bbdm-svc:v_20210721112225
          imagePullPolicy: IfNotPresent
          workingDir: /root
          volumeMounts:
          - name: bbdm-conf
            mountPath: /root/bbdm/conf
          ports:
          - name: web
            containerPort: 8081
            hostPort: 8081
          resources:
            limits:
              cpu: 1Gi
              memory: 6Gi
            requests:
              cpu: 1m
              memory: 1m
          livenessProbe:
            httpGet:
              path: /ocr/actuator/health
              port: 8081
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 10
        volumes:
        - name: bbdm-conf
          configMap:
            name: bbdm-conf



---

apiVersion: v1
kind: Service
metadata:
  name: bbdm-svc
  namespace: 4pd
spec:
  type: NodePort
  ports:
  - name: web
    protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30001
  selector:
    app: hsbc-bbdm


---
apiVersion: v1
kind: Namespace
metadata:
  name: 4pd
