apiVersion: v1
kind: Pod
metadata:
  name: bbdm-service
  namespace: 4pd
  labels:
    - hsbc-ocr-real-predictor: true
  spec:
    containers:
      - name: bbdm-service
        images: $image
        imagePullPolice: IfNotPresent
        ports:
          - name: web
            containerPort: 8080
            hostPort: 8080
        resources:
          limits:
            cpu:
            memory:
          requests:
            cpu:
            memory:
        livenessProbe:
          httpGet:
            path: /api/ocr/
            port: 8080
            initialDelaySeconds:
            timeoutSeconds:
            periodSeconds:
            successThreshold:
            failureThreshold:
        restartPolicy: OnFailure

