FROM openjdk:8u102-jdk
MAINTAINER wujian@4paradigm.com
USER root
WORKDIR /root
RUN mkdir /root/bbdm &&  chmod -R 777 /root/bbdm
COPY ./bbdm/ /root/bbdm/
ENTRYPOINT ["/bin/bash","/root/bbdm/bin/start.sh"]
