CREATE TABLE `ocr_real_predictor` (
  `id` bigint(20) NOT NULL,
  `cases_id` bigint(20) NOT NULL,
  `doc_id` bigint(20) NOT NULL,
  `inst_id` bigint(20) NOT NULL,
  `page_id` bigint(20) NOT NULL COMMENT 'document',
  `value_type` varchar(125) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'amountcurrencybeneficiaryapplicant',
  `value` varchar(1024) COLLATE utf8mb4_bin DEFAULT NULL,
  `comment` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL,
  `ocr_name` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'ocr',
  `ocr_value` varchar(1024) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'ocr',
  `ocr_boxes` varchar(1024) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'ocr',
  `ocr_texts` varchar(1024) COLLATE utf8mb4_bin DEFAULT NULL,
  `status` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'pendingcompleted',
  `create_time` datetime DEFAULT NULL,
  `create_user` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL,
  `last_modified_time` datetime DEFAULT NULL,
  `last_modified_user` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL,
  `version` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_doc_item_casesid` (`cases_id`),
  KEY `idx_doc_item_docId` (`doc_id`),
  KEY `idx_doc_item_docIdpageid` (`doc_id`,`page_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin