spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true



server:
  servlet:
    context-path: /ocr
  port: 8092

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

